# Generated by Django 6.0.1 on 2026-01-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_id", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("course_name", models.CharField(blank=True, max_length=100)),
                ("personal_info_completed", models.BooleanField(default=False)),
                ("documents_uploaded", models.BooleanField(default=False)),
                ("payment_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("select", "Select"),
                            ("resume", "Resume"),
                            ("passport", "Passport"),
                            ("identity card", "Identity Card"),
                            ("certificate", "Certificate"),
                            ("registration payment slip", "Registration Payment Slip"),
                            ("high school certificate", "High School Certificate"),
                            ("transcript", "Transcript"),
                            ("nin", "NIN"),
                        ],
                        max_length=100,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("mr", "Mr"), ("mrs", "Mrs"), ("dr", "Dr")],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("address", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("marital_status", models.CharField(blank=True, max_length=100)),
                ("title_of_course", models.CharField(blank=True, max_length=255)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                (
                    "institution_attended_line_one",
                    models.CharField(blank=True, max_length=250),
                ),
                (
                    "institution_attended_line_two",
                    models.CharField(blank=True, max_length=250),
                ),
                (
                    "institution_attended_line_three",
                    models.CharField(blank=True, max_length=250),
                ),
                (
                    "institution_attended_line_four",
                    models.CharField(blank=True, max_length=250),
                ),
                ("date_of_award", models.DateField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=255)),
                ("grade", models.CharField(blank=True, max_length=100)),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("employer", models.CharField(blank=True, max_length=255)),
                ("office_address", models.CharField(blank=True, max_length=300)),
                ("office_duties", models.CharField(blank=True, max_length=300)),
                ("company_name", models.CharField(blank=True, max_length=300)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("select", "Select"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_photos/")),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                    ),
                ),
            ],
        ),
    ]
