# Generated by Django 6.0.1 on 2026-01-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_applicationdocument_uploaded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="application",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="created_at",
            new_name="submitted_at",
        ),
        migrations.AddField(
            model_name="application",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="company_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="application",
            name="date_of_award",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="application",
            name="employer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="father_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="institution_attended_line_four",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="application",
            name="institution_attended_line_one",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="application",
            name="institution_attended_line_three",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="application",
            name="institution_attended_line_two",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="application",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="language",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="marital_status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="office_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="application",
            name="office_duties",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_school",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="program",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="application",
            name="qualification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="application",
            name="title",
            field=models.CharField(
                choices=[("mr", "Mr"), ("mrs", "Mrs"), ("dr", "Dr")],
                default="dr",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications_as_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications_as_applicant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "pending"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ApplicationFormData",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
