# Generated by Django 6.0.1 on 2026-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_payment_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="employer_name",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
