# Generated by Django 6.0.1 on 2026-01-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_application_employer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="employer_name",
        ),
    ]
