# Generated by Django 6.0.1 on 2026-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_application_employer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="employer",
        ),
        migrations.AddField(
            model_name="application",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("employed", "Employed"),
                    ("self-employed", "Self-Employed"),
                    ("unemployed", "unemployed"),
                ],
                default="unemployed",
                max_length=20,
            ),
        ),
    ]
