# Generated by Django 6.0.1 on 2026-01-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_remove_application_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("employed", "Employed"),
                    ("self-employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                ],
                default="unemployed",
                max_length=20,
            ),
        ),
    ]
