# Generated by Django 6.0.1 on 2026-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_alter_application_employment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="application",
            name="course_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="application",
            name="father_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="application",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="application",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
