# Generated by Django 6.0.1 on 2026-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0008_application_department_alter_application_course_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="institution_attended_line_four",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="application",
            name="institution_attended_line_one",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="application",
            name="institution_attended_line_three",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="application",
            name="institution_attended_line_two",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="application",
            name="qualification",
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
