# Generated by Django 6.0.1 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0009_alter_application_institution_attended_line_four_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_qualifications",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
