# Generated by Django 6.0.1 on 2026-01-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_application_additional_qualifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="office_duties",
            new_name="position_held",
        ),
    ]
