# Generated by Django 6.0.1 on 2026-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_rename_office_duties_application_position_held"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="degree",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
