# Generated by Django 6.0.1 on 2026-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_application_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile_phicture.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
