# Generated by Django 6.0.1 on 2026-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_application_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile_picture.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
