# Generated by Django 6.0.1 on 2026-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_alter_application_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="todays_date",
            field=models.DateField(auto_now=True),
        ),
    ]
