# Generated by Django 6.0.1 on 2026-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
