# Generated by Django 6.0.1 on 2026-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
