# Generated by Django 6.0.1 on 2026-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("application_fee", "Application Fee"),
                    ("school_fee", "School Fee"),
                ],
                max_length=30,
            ),
        ),
    ]
